master/datamill_django_project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from wiki.urls import get_pattern as get_wiki_pattern
from django_notify.urls import get_pattern as get_notify_pattern

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('datamill_website.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),



)

urlpatterns += patterns('',
    (r'^notify/', get_notify_pattern()),
    (r'^wiki/', get_wiki_pattern())
    )

master/datamill_website/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from django.contrib import admin

from datamill_website import views
from decorators import *

admin.autodiscover()

urlpatterns = patterns(
    '',

    # landing, about, etc 
    url(r'^$', 'datamill_website.views.home', name='home'),
    url(r'about/$', 'datamill_website.views.about', name='about'),
    url(r'sponsors/$', 'datamill_website.views.sponsors', name='sponsors'),
    url(r'institutions/$', 'datamill_website.views.institutions', name='institutions'),

    # wizard
    url(r'^experiment/add/$', login_required(views.experiment_add), name='experiment_add'),
    url(r'^experiment/tag-hint/$', login_required(views.tag_hint), name='tag_hint'),
    # edit title and description
    url(r'^experiment/save/(?P<pk>\d+)/$', login_required(views.experiment_save), name='experiment_save'),
    # clone
    url(r'^experiment/clone/(?P<pk>\d+)/$', login_required(views.experiment_add), name='experiment_clone'),
    # delete
    url(r'^experiment/delete/(?P<pk>\d+)/$', login_required(views.experiment_delete), name='experiment_delete'),

    # individual detail views
    url(r'^job/(?P<pk>\d+)/$', login_required(views.job_detail), name='job_detail'),
    url(r'^worker/(?P<pk>\d+)/$', login_required(views.worker_detail), name='worker_detail'),
    url(r'^experiment/(?P<pk>\d+)/$', login_required(views.experiment_detail), name='experiment_detail'),

    # log file downloads
    url(r'job/(?P<pk>\d+)/log/(?P<log_name>\w+)/$', login_required(views.job_status_log), name='job_status_log'),

    # list views
    url(r'^jobs/$', login_required(views.job_list), name='jobs'),
    url(r'^workers/new/$', login_required(views.new_worker_list), name='new_workers'),
    url(r'^workers/register/$', login_required(views.register_worker), name='register_worker'),
    url(r'^workers/$', login_required(views.worker_list), name='workers'),
    url(r'^experiments/$', login_required(views.experiment_list), name='experiments'),

    # file serving
    url(r'^package/(?P<pk>\d+)/$', login_required(views.package), name='package'),
    url(r'^job_results/(?P<pk>\d+)/$', login_required(views.job_results), name='job_results'),
    url(r'^job_status/(?P<pk>\d+)/$', login_required(views.job_status), name='job_status'),
    url(r'^experiment_results/(?P<pk>\d+)/$', login_required(views.experiment_results), name='experiment_results'),

    # account mgmt
    url(r'^login/$', 'datamill_website.views.home', name='home'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^register/$', 'datamill_website.views.create_account', name="create_account"),
    url(r'^user/password/change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'random_password/$', 'datamill_website.views.random_password', name='random_password'),
    url(r'^user/password/change/done/$', 'django.contrib.auth.views.password_change_done',),
    url(r'^user/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/user/password/reset/done/', 'from_email': settings.DATAMILL_EMAIL},
        name="password_reset"),
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/user/password/done/'}),
    url(r'^user/password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete'),

    # actions
    url(r'^experiment_cancel/(?P<pk>\d+)/$', login_required(views.experiment_cancel), name='experiment_cancel'),
    url(r'^experiment_publish/(?P<pk>\d+)/$', login_required(views.experiment_publish), name='experiment_publish'),
    url(r'^experiment_make_private/(?P<pk>\d+)/$', login_required(views.experiment_make_private), name='experiment_make_private'),
    url(r'^experiment_retry/(?P<pk>\d+)/$', login_required(views.experiment_retry), name='experiment_retry'),

    # admin
    url(r'^workers/manage/$', is_superuser(views.worker_monitor), name='worker_manage'),
    url(r'^worker/(?P<pk>\d+)/jobs/cancel/$', is_superuser(views.cancel_worker_jobs), name='cancel_worker_jobs'),
)

master/datamill_website/models.py
from django.conf import settings
from django.db import models
from django.db import connection
from django.db.models import Max, Min
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db.models import Q
from datetime import datetime, timedelta
from taggit.managers import TaggableManager
import sys
import os
import os.path
import shutil
import csv
import subprocess
import json
import reversion
from pwd import getpwnam
from grp import getgrnam
import stat
import math
from django.core.files.storage import FileSystemStorage

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User, Group
from django.contrib.sites.models import Site
from django.db import transaction #TODO will commit_on_success will become atomic() in 1.6
from guardian.shortcuts import assign_perm, remove_perm, get_users_with_perms, get_perms_for_model, get_objects_for_group

from md5hash import md5hash

import logging, glob
import pwd
import grp
from django.db.models import signals
from django.core.files import File
from reversion.models import Version
if len(sys.argv) > 1 and sys.argv[1] != None:
    logger = logging.getLogger('{0}.models'.format(sys.argv[1]))
else:
    logger = logging.getLogger('datamill_models')

###########################################
# DATAMILL MODELS:
###########################################

class WorkerManager(models.Manager):
    def available(self):
        return self.exclude(status=Worker.DEAD)

def change_owner_to_apache(filename):
    try:
        apache_uid = pwd.getpwnam('apache').pw_uid
    except KeyError:
        apache_uid = os.getuid() # current process when running without apache

    return os.chown(filename, apache_uid, -1) # leave group id alone

class News(models.Model):
    title = models.CharField(default='Enter title here', max_length=120)
    body = models.TextField(default='')
    day = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'news'

class Worker(models.Model):
    IDLE = 'ID'
    WORKING = 'WR'
    DEAD = 'DE'
    WORKER_STATUS_CHOICES = (
           (IDLE, 'Idle'),
           (WORKING, 'Working'),
           (DEAD, 'Dead'),
           )

    status = models.CharField('status', max_length=2, choices=WORKER_STATUS_CHOICES,
            default=IDLE)
    uuid = models.CharField('UUID', max_length=36, unique=True)
    hello_version = models.CharField('software version', max_length=30)

    last_update = models.DateTimeField('last update to worker information', auto_now_add=True)
    user = models.ForeignKey(User, default=settings.DEFAULT_WORKER_OWNER_ID)

    # non-critical metadata from here on
    ip = models.IPAddressField('IP')
    hostname = models.CharField('hostname', max_length=30)
    # these are not considered factors
    cpu_model = models.CharField('CPU architecture', max_length=128)
    cpu_flags = models.TextField('CPU flags')
    gpu_model = models.CharField('GPU architecture', max_length=128, default='N/A')
    gpu_flags = models.TextField('GPU flags', default='N/A')
    ram_type = models.CharField('RAM type', max_length=128, default='N/A')
    objects = WorkerManager()

    def __unicode__(self):
        return '{} - {} - {}'.format(self.hostname, self.ip, self.uuid)

    # datamill methods
    def current_experiment(self):
        if self.job_set.filter(status=Job.IN_PROGRESS).count() > 1:
            return self.job_set.filter(status=Job.IN_PROGRESS).order_by('-id')[0].experiment
        else:
            return self.job_set.get(status=Job.IN_PROGRESS).experiment

    def job_queue(self):
        return self.job_set.filter(status__in=[ Job.IN_PROGRESS, Job.QUEUED ])

    def get_hardware_level(self, factor_internal_name, date=None):
        if not date:
            return self.workerfeature_set.get(level__factor=Factor.objects.get(internal_name=factor_internal_name)).level.internal_name
        else:
            # fields in the worker model are not hardware factors
            for field in self._meta.fields:
                if factor_internal_name == field.name:
                    raise Exception('{} is not a factor'.format(factor_internal_name))
            if Factor.objects.filter(internal_name=factor_internal_name).exists():
                worker_feature = self.workerfeature_set.get(level__factor=Factor.objects.get(internal_name=factor_internal_name))
                try:
                    # Find the most recent version for a given date:
                    version = reversion.get_for_date(worker_feature, date)
                    # Access the model data stored within the version:
                    version_data = version.field_dict
                    return Level.objects.get(id=version_data['level']).internal_name
                except Version.DoesNotExist:
                    return worker_feature.level.internal_name

    def get_dir(self):
        return os.path.join(settings.DATAMILL_FTP_ROOT, 'worker-{0}'.format(self.uuid))

    def make_dead(self):
        self.status = Worker.DEAD
        pending_jobs = self.job_queue()

        for j in pending_jobs:
            j.fail()

        self.save()
        if os.path.isdir(self.get_dir()):
            shutil.rmtree(self.get_dir())

    def update_status(self):

        if not self.status == Worker.DEAD: # can't come back from the dead

            if self.job_set.filter(status=Job.IN_PROGRESS).exists():
                self.status = Worker.WORKING
            else:
                self.status = Worker.IDLE

            # the following query gets the max update time between this worker's jobs
            # it may return None if the worker hasn't done anything yet
            # in that case, we maintain the existing last_update (i.e., worker creation time)

            candidate_last_update = self.job_set.filter(
                    status__in=[ Job.IN_PROGRESS, Job.DONE, Job.FAILED ]).aggregate(
                            Max('last_update'))['last_update__max']

            if candidate_last_update:
                # in case of rereg, self.last_update will > candidate_last_update and should be retained
                self.last_update = max(self.last_update, candidate_last_update)

            # get the oldest still-queued job (most stale)
            # may return none if there's no pending jobs
            oldest_queue_time = self.job_set.filter(status=Job.QUEUED).aggregate(
                            Min('last_update'))['last_update__min']

            # if I'm expecting to hear from the worker (i.e., jobs are waiting)
            #   if he's not said anything in a long time
            #       then it's dead

            if self.job_set.filter(status__in=[Job.IN_PROGRESS, Job.QUEUED]).exists():
                if not oldest_queue_time: oldest_queue_time = datetime.min # cover when only in_prog exists

                effective_last_update = max(oldest_queue_time, self.last_update)

                if (datetime.now() - effective_last_update).days > settings.DATAMILL_DAYS_UNTIL_WORKER_DEAD:
                    self.make_dead()
                    return

            self.save()

    @reversion.create_revision()
    def fill_from_dict(self, dict):
        # attention: now calls self.save()

        # this method fills in as much as it can, ignoring missing data.
        # if any missing field turns out to be important or if any
        # of the values filled turn out to be bogus we catch it when we
        # call save() on this worker.

        # extraneous fields in the dict are ignored.

        try:
            with transaction.commit_on_success():
                for field in self._meta.fields:
                    if dict.has_key(field.name):
                        setattr(self, field.name, dict[field.name])

                self.save()

                for factor in Factor.objects.all():
                    if dict.has_key(factor.internal_name):
                        if isinstance(dict[factor.internal_name], list):
                            WorkerFeature.objects.filter(worker=self, level__factor__internal_name=factor.internal_name).delete()
                            for level_name in dict[factor.internal_name]:
                                level, created = Level.objects.get_or_create(factor=factor, internal_name=str(level_name))
                                feature, created = WorkerFeature.objects.get_or_create(worker=self, level=level)
                        else:
                            level, created = Level.objects.get_or_create(factor=factor, internal_name=str(dict[factor.internal_name]))
                            # assumes there is only one level per worker and factor pair
                            if WorkerFeature.objects.filter(worker=self, level__factor=level.factor).exists():
                                feature = WorkerFeature.objects.get(worker=self, level__factor=level.factor)
                                feature.level = level
                                feature.save()
                            else:
                                WorkerFeature.objects.create(worker=self, level=level)
                    else:
                        raise Exception('factor is missing in dictionary: {}'.format(factor.internal_name))

        except Exception:
            if Worker.objects.filter(uuid=self.uuid).exists(): # if I was in the db
                self.make_dead()
            raise

    def create_dir(self):
        if not os.path.exists(self.get_dir()):
            os.mkdir(self.get_dir())

            try:
                uid = getpwnam('apache')[2]
                gid = getgrnam('ftp')[2]
                os.chown(self.get_dir(), uid, gid)
                os.chmod(self.get_dir(),
                                stat.S_IRUSR |
                                stat.S_IWUSR |
                                stat.S_IXUSR |
                                stat.S_IRGRP |
                                stat.S_IWGRP |

master/datamill_website/forms.py
from datamill_website.models import Experiment, Package

from django.forms import ModelForm, Textarea
from django import forms
from django.contrib.auth.models import User

class PackageForm(forms.ModelForm):
    class Meta:
        model = Package
        exclude = ('experiment',)

class NumberInput(forms.widgets.TextInput):
    input_type = 'number'

class ExperimentForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea, required=False)
    class Meta:
        model = Experiment
        fields = ['name', 'replicate_count', 'run_on_all_workers', 'tags']

    replicate_count = forms.IntegerField(
            min_value = 1,
            widget = NumberInput(attrs={'data-bind': 'value: numReplicates', 'class': 'input-mini'})
    )

class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

master/datamill_website/templates/wiki/includes/anonymous_blocked.html
{% load i18n %}
{% load url from future %}
<em>
{% url 'wiki:signup' as signup_url %}
{% url 'wiki:login' as login_url %}
{% if login_url and signup_url %}
  {% blocktrans %}
  You need to <a href="{{ login_url }}">log in</a> or <a href="{{ signup_url }}">sign up</a> to use this function.
  {% endblocktrans %}
{% else %}
  {% trans "You need to log in or sign up to use this function." %}
{% endif %}
</em>

master/datamill_website/templates/wiki/includes/article_menu.html
{% load i18n wiki_tags %}{% load url from future %}

{% with selected_tab as selected %}

<li class="pull-right{% if selected == "settings" %} active{% endif %}">
  {% if not user.is_anonymous %}
  <a href="{% url 'wiki:settings' article_id=article.id path=urlpath.path %}">
    <span class="icon-wrench"></span>
    {% trans "Settings" %}
  </a>
  {% endif %}
</li>

{% for plugin in article_tabs %}
  <li class="pull-right{% if selected == plugin.slug %} active{% endif %}">
    <a href="{% url 'wiki:plugin' slug=plugin.slug article_id=article.id path=urlpath.path %}">
      <span class="{{ plugin.article_tab.1 }}"></span>
      {{ plugin.article_tab.0 }}
    </a>
  </li>
{% endfor %}

<li class="pull-right{% if selected == "history" %} active{% endif %}">
  <a href="{% url 'wiki:history' article_id=article.id path=urlpath.path %}">
    <span class="icon-time"></span>
    {% trans "Changes" %}
  </a>
</li>

{% if article|can_write:user and not article.current_revision.locked %}
<li class="pull-right{% if selected == "edit" %} active{% endif %}">
  <a href="{% url 'wiki:edit' article_id=article.id path=urlpath.path %}">
    <span class="icon-edit"></span>
    {% trans "Edit" %}
  </a>
</li>
{% else %}
<li class="pull-right{% if selected == "source" %} active{% endif %}">
  <a href="{% url 'wiki:source' article_id=article.id path=urlpath.path %}">
    <span class="icon-lock"></span>
    {% trans "View Source" %}
  </a>
</li>
{% endif %}

<li class="pull-right{% if selected == "view" %} active{% endif %}">
  <a href="{% url 'wiki:get' article_id=article.id path=urlpath.path %}">
    <span class="icon-home"></span>
    {% trans "View" %}
  </a>
</li>

{% endwith %}

master/datamill_website/templates/wiki/includes/breadcrumbs.html
{% load i18n %}{% load url from future %}
{% if urlpath %}
<div id="article-breadcrumbs">

<ul class="breadcrumb pull-left">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="{% url 'wiki:root' %}">Wiki</a> <span class="divider">/</span></li>
  {% for ancestor in urlpath.cached_ancestors %}
    <li><a href="{% url 'wiki:get' path=ancestor.path %}">{{ ancestor.article.current_revision.title|truncatechars:25 }}</a> <span class="divider">/</span></li>
  {% endfor %}
  <li class="active">{{ article.current_revision.title|truncatechars:25 }}</li>
</ul>

<div style="clear: both"></div>
</div>
{% endif %}

master/datamill_website/templates/wiki/includes/editor.html
{% load wiki_tags i18n sekizai_tags %}
{% include "wiki/includes/editormedia.html" %}

{% wiki_form form %}
{% addtoblock "js" %}
<script language="javascript">
  $(document).ready(function() {
    $("#id_revision").val('{{ article.current_revision.id }}');
  });
</script>
{% endaddtoblock %}

master/datamill_website/templates/wiki/includes/editor_sidebar.html
{% load i18n sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript">
  $(document).ready( function() {
    $('.sidebar-form').each(function () {
      $(this).submit( function() {
        this.unsaved_article_title.value = $('#id_title').val();
        this.unsaved_article_content.value = $('#id_content').val();
      });
    });
  });
</script>
{% endaddtoblock %}

<div class="accordion" id="accordion_{{ plugin.slug }}">

{% for plugin, plugin_form in sidebar %}

  <div class="accordion-group">
    
    <div class="accordion-heading">
      <a class="accordion-toggle" href="#collapse_{{ plugin.slug }}" data-toggle="collapse">
        <h3>{{ plugin.sidebar.headline }} <span class="{{ plugin.sidebar.icon_class }}"></span></h3>
      </a>
    </div>
    
    <div id="collapse_{{ plugin.slug }}" class="accordion-body collapse{% if plugin_form.errors %} in{% endif %}">
      <div class="accordion-inner form-vertical">
        {% if plugin.sidebar.template %}
          {% with plugin_form as form and plugin as plugin %}
            <form method="POST" class="form-horizontal sidebar-form" action="?f={{ plugin_form.form_id }}" enctype="multipart/form-data">
              {% csrf_token %}
              {% include plugin.sidebar.template %}
            </form>
          {% endwith %}
        {% endif %}
      </div>
    </div>
  
  </div>
{% endfor %}
</div>

master/datamill_website/templates/wiki/includes/editormedia.html
{% load sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/editor.js"></script>
{% for js in editor.Media.js %}
<script type="text/javascript" src="{{ STATIC_URL }}{{ js }}"></script>
{% endfor %}
{% endaddtoblock %}

{% addtoblock "css" %}
{% for media, srcs in editor.Media.css.items %}
  {% for src in srcs %}
    <link rel="stylesheet" media="{{ media }}" href="{{ STATIC_URL }}{{ src }}" />
  {% endfor %}
{% endfor %}
{% endaddtoblock %}

master/datamill_website/templates/wiki/includes/form.html
{% csrf_token %}{% load sekizai_tags %}
{% if form.non_field_errors %}
  {% if form_error_title %}<h4 class="alert-heading">{{ form_error_title }}</h4>{% endif %}
  {% for error_message in form.non_field_errors %}
    <div class="alert alert-block alert-error">
      {{ error_message }}
    </div>    
  {% endfor %}
{% endif %}

{% addtoblock "js" %}
{{ form.media.js }}
{% endaddtoblock %}

{% addtoblock "css" %}
{{ form.media.css }}
{% endaddtoblock %}

{% for field in form %}

  {% if field.is_hidden %}
    {{ field }}
  {% else %}
  
  <div id="div_{{ field.auto_id }}" class="clearfix control-group{% if field.errors %} error{% endif %}">
    {% if field.label %}
      <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
      {{ field.label|safe }}
      </label>
    {% endif %}
    <div class="controls">
      {{ field }} {% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
      {% if field.errors %}
        {% for error in field.errors %}
          <div id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></div>
        {% endfor %}
      {% endif %}
      {% if field.help_text %}
        <p id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</p>
      {% endif %}
    </div>
  </div>
  {% endif %}

{% endfor %}

master/datamill_website/templates/wiki/includes/modals.html
{% load sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/jqueryui/jquery-ui-1.10.0.custom.min.js"></script>
<script type="text/javascript">
// $modal: the jQuery modal object
function resizeModal($modal) {
  var windowHeight = $(window).height();
  var windowWidth = $(window).width();
  var leftMargin = (windowWidth - $modal.width()) / 2;
  $modal.css({left: leftMargin});
  $modal.height(windowHeight - 160);
  $('.modal-body', $modal).height($modal.height() - 110);
}

$(document).ready(function() {
  
  $(".modal-full").on("show", function(event) {
    $('<div class="iframe-loader alert">').prependTo('.modal-body', $(this)).text('Loading ... ');
    $('iframe', $(this)).hide();
    resizeModal($(this));
  });
  
  $(window).on('resize', function(event, ui){
    $(".modal-full").filter(":visible").each(function(index, element) {
      resizeModal($(element));
    });
  });
  
  $('iframe', '.modal-full').load(function() {
    $('.iframe-loader', '.modal-full').remove();
    $(this).show();
  });

});
</script>
{% endaddtoblock %}

master/datamill_website/templates/wiki/includes/pagination.html
{% load i18n %}
{% if is_paginated %}
<div class="pagination clearfix">
  <ul class="pull-right">
    {% for pc in paginator.page_range %}
    <li class="{% if pc == page_obj.number %} active{% endif %}"><a href="?page={{ pc }}{% if appended_key %}&{{ appended_key }}={{ appended_value }}{% endif %}">{{ pc }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endif %}

master/datamill_website/templates/wiki/includes/render.html
{% load wiki_tags i18n cache sekizai_tags %}

{% addtoblock "js" %}        
  <!--<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/article.js"></script>-->
{% endaddtoblock %}

<div class="wiki-article">
  {% if not preview %}

    {% if article.current_revision %}
      {{ article.get_cached_content }}
    {% endif %}

  {% else %}

    {{ content|default:"" }}
    
    {% addtoblock "css" %}
      <link type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/wiki-preview.css" />
    {% endaddtoblock %}

  {% endif %}
  
</div>

{% for plugin in plugins %}
  {% if plugin.RenderMedia.css %}
    {% addtoblock "css" %}
      {% for media, url in plugin.RenderMedia.css.items %}
        <link rel="stylesheet" href="{{ STATIC_URL }}{{ url }}" />
      {% endfor %}
    {% endaddtoblock %}
  {% endif %}
  {% if plugin.RenderMedia.js %}
    {% addtoblock "js" %}        
      {% for url in plugin.RenderMedia.js %}
        <script type="text/javascript" src="{{ STATIC_URL }}{{ url }}"></script>
      {% endfor %}
    {% endaddtoblock %}
  {% endif %}
{% endfor %}

master/datamill_website/templates/wiki/includes/revision_info.html
{% comment %}

  This reusable code is shared between different templates and different inheritors of
  BaseRevision.

{% endcomment %}


{% load wiki_tags i18n %}
{% if not hidedate %}{{ revision.created }}{% endif %} {% if not hidenumber %}(#{{ revision.revision_number }}) {% trans "by" %}{% endif %} {% if revision.user %}{{ revision.user }}{% else %}{% if article|can_moderate:user %}{{ revision.ip_address|default:"anonymous (IP not logged)" }}{% else %}{% trans "anonymous (IP logged)" %}{% endif %}{% endif %}
{% if revision == current_revision %}
  <strong>*</strong>
{% endif %}
{% if revision.deleted %}
<span class="badge badge-important">{% trans "deleted" %}</span>
{% endif %}
{% if revision.previous_revision.deleted and not revision.deleted %}
<span class="badge badge-success">{% trans "restored" %}</span>
{% endif %}
{% if revision.locked %}
<span class="badge">{% trans "locked" %}</span>
{% endif %}
{% if revision.previous_revision.locked and not revision.locked %}
<span class="badge">{% trans "unlocked" %}</span>
{% endif %}