master/datamill_django_project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from wiki.urls import get_pattern as get_wiki_pattern
from django_notify.urls import get_pattern as get_notify_pattern

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('datamill_website.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),



)

urlpatterns += patterns('',
    (r'^notify/', get_notify_pattern()),
    (r'^wiki/', get_wiki_pattern())
    )

master/datamill_website/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from django.contrib import admin

from datamill_website import views
from decorators import *

admin.autodiscover()

urlpatterns = patterns(
    '',

    # landing, about, etc 
    url(r'^$', 'datamill_website.views.home', name='home'),
    url(r'about/$', 'datamill_website.views.about', name='about'),
    url(r'sponsors/$', 'datamill_website.views.sponsors', name='sponsors'),
    url(r'institutions/$', 'datamill_website.views.institutions', name='institutions'),

    # wizard
    url(r'^experiment/add/$', login_required(views.experiment_add), name='experiment_add'),
    url(r'^experiment/tag-hint/$', login_required(views.tag_hint), name='tag_hint'),
    # edit title and description
    url(r'^experiment/save/(?P<pk>\d+)/$', login_required(views.experiment_save), name='experiment_save'),
    # clone
    url(r'^experiment/clone/(?P<pk>\d+)/$', login_required(views.experiment_add), name='experiment_clone'),
    # delete
    url(r'^experiment/delete/(?P<pk>\d+)/$', login_required(views.experiment_delete), name='experiment_delete'),

    # individual detail views
    url(r'^job/(?P<pk>\d+)/$', login_required(views.job_detail), name='job_detail'),
    url(r'^worker/(?P<pk>\d+)/$', login_required(views.worker_detail), name='worker_detail'),
    url(r'^experiment/(?P<pk>\d+)/$', login_required(views.experiment_detail), name='experiment_detail'),

    # log file downloads
    url(r'job/(?P<pk>\d+)/log/(?P<log_name>\w+)/$', login_required(views.job_status_log), name='job_status_log'),

    # list views
    url(r'^jobs/$', login_required(views.job_list), name='jobs'),
    url(r'^workers/new/$', login_required(views.new_worker_list), name='new_workers'),
    url(r'^workers/register/$', login_required(views.register_worker), name='register_worker'),
    url(r'^workers/$', login_required(views.worker_list), name='workers'),
    url(r'^experiments/$', login_required(views.experiment_list), name='experiments'),

    # file serving
    url(r'^package/(?P<pk>\d+)/$', login_required(views.package), name='package'),
    url(r'^job_results/(?P<pk>\d+)/$', login_required(views.job_results), name='job_results'),
    url(r'^job_status/(?P<pk>\d+)/$', login_required(views.job_status), name='job_status'),
    url(r'^experiment_results/(?P<pk>\d+)/$', login_required(views.experiment_results), name='experiment_results'),

    # account mgmt
    url(r'^login/$', 'datamill_website.views.home', name='home'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^register/$', 'datamill_website.views.create_account', name="create_account"),
    url(r'^user/password/change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'random_password/$', 'datamill_website.views.random_password', name='random_password'),
    url(r'^user/password/change/done/$', 'django.contrib.auth.views.password_change_done',),
    url(r'^user/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/user/password/reset/done/', 'from_email': settings.DATAMILL_EMAIL},
        name="password_reset"),
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/user/password/done/'}),
    url(r'^user/password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete'),

    # actions
    url(r'^experiment_cancel/(?P<pk>\d+)/$', login_required(views.experiment_cancel), name='experiment_cancel'),
    url(r'^experiment_publish/(?P<pk>\d+)/$', login_required(views.experiment_publish), name='experiment_publish'),
    url(r'^experiment_make_private/(?P<pk>\d+)/$', login_required(views.experiment_make_private), name='experiment_make_private'),
    url(r'^experiment_retry/(?P<pk>\d+)/$', login_required(views.experiment_retry), name='experiment_retry'),

    # admin
    url(r'^workers/manage/$', is_superuser(views.worker_monitor), name='worker_manage'),
    url(r'^worker/(?P<pk>\d+)/jobs/cancel/$', is_superuser(views.cancel_worker_jobs), name='cancel_worker_jobs'),
)

master/datamill_website/models.py
from django.conf import settings
from django.db import models
from django.db import connection
from django.db.models import Max, Min
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db.models import Q
from datetime import datetime, timedelta
from taggit.managers import TaggableManager
import sys
import os
import os.path
import shutil
import csv
import subprocess
import json
import reversion
from pwd import getpwnam
from grp import getgrnam
import stat
import math
from django.core.files.storage import FileSystemStorage

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User, Group
from django.contrib.sites.models import Site
from django.db import transaction #TODO will commit_on_success will become atomic() in 1.6
from guardian.shortcuts import assign_perm, remove_perm, get_users_with_perms, get_perms_for_model, get_objects_for_group

from md5hash import md5hash

import logging, glob
import pwd
import grp
from django.db.models import signals
from django.core.files import File
from reversion.models import Version
if len(sys.argv) > 1 and sys.argv[1] != None:
    logger = logging.getLogger('{0}.models'.format(sys.argv[1]))
else:
    logger = logging.getLogger('datamill_models')

###########################################
# DATAMILL MODELS:
###########################################

class WorkerManager(models.Manager):
    def available(self):
        return self.exclude(status=Worker.DEAD)

def change_owner_to_apache(filename):
    try:
        apache_uid = pwd.getpwnam('apache').pw_uid
    except KeyError:
        apache_uid = os.getuid() # current process when running without apache

    return os.chown(filename, apache_uid, -1) # leave group id alone

class News(models.Model):
    title = models.CharField(default='Enter title here', max_length=120)
    body = models.TextField(default='')
    day = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'news'

class Worker(models.Model):
    IDLE = 'ID'
    WORKING = 'WR'
    DEAD = 'DE'
    WORKER_STATUS_CHOICES = (
           (IDLE, 'Idle'),
           (WORKING, 'Working'),
           (DEAD, 'Dead'),
           )

    status = models.CharField('status', max_length=2, choices=WORKER_STATUS_CHOICES,
            default=IDLE)
    uuid = models.CharField('UUID', max_length=36, unique=True)
    hello_version = models.CharField('software version', max_length=30)

    last_update = models.DateTimeField('last update to worker information', auto_now_add=True)
    user = models.ForeignKey(User, default=settings.DEFAULT_WORKER_OWNER_ID)

    # non-critical metadata from here on
    ip = models.IPAddressField('IP')
    hostname = models.CharField('hostname', max_length=30)
    # these are not considered factors
    cpu_model = models.CharField('CPU architecture', max_length=128)
    cpu_flags = models.TextField('CPU flags')
    gpu_model = models.CharField('GPU architecture', max_length=128, default='N/A')
    gpu_flags = models.TextField('GPU flags', default='N/A')
    ram_type = models.CharField('RAM type', max_length=128, default='N/A')
    objects = WorkerManager()

    def __unicode__(self):
        return '{} - {} - {}'.format(self.hostname, self.ip, self.uuid)

    # datamill methods
    def current_experiment(self):
        if self.job_set.filter(status=Job.IN_PROGRESS).count() > 1:
            return self.job_set.filter(status=Job.IN_PROGRESS).order_by('-id')[0].experiment
        else:
            return self.job_set.get(status=Job.IN_PROGRESS).experiment

    def job_queue(self):
        return self.job_set.filter(status__in=[ Job.IN_PROGRESS, Job.QUEUED ])

    def get_hardware_level(self, factor_internal_name, date=None):
        if not date:
            return self.workerfeature_set.get(level__factor=Factor.objects.get(internal_name=factor_internal_name)).level.internal_name
        else:
            # fields in the worker model are not hardware factors
            for field in self._meta.fields:
                if factor_internal_name == field.name:
                    raise Exception('{} is not a factor'.format(factor_internal_name))
            if Factor.objects.filter(internal_name=factor_internal_name).exists():
                worker_feature = self.workerfeature_set.get(level__factor=Factor.objects.get(internal_name=factor_internal_name))
                try:
                    # Find the most recent version for a given date:
                    version = reversion.get_for_date(worker_feature, date)
                    # Access the model data stored within the version:
                    version_data = version.field_dict
                    return Level.objects.get(id=version_data['level']).internal_name
                except Version.DoesNotExist:
                    return worker_feature.level.internal_name

    def get_dir(self):
        return os.path.join(settings.DATAMILL_FTP_ROOT, 'worker-{0}'.format(self.uuid))

    def make_dead(self):
        self.status = Worker.DEAD
        pending_jobs = self.job_queue()

        for j in pending_jobs:
            j.fail()

        self.save()
        if os.path.isdir(self.get_dir()):
            shutil.rmtree(self.get_dir())

    def update_status(self):

        if not self.status == Worker.DEAD: # can't come back from the dead

            if self.job_set.filter(status=Job.IN_PROGRESS).exists():
                self.status = Worker.WORKING
            else:
                self.status = Worker.IDLE

            # the following query gets the max update time between this worker's jobs
            # it may return None if the worker hasn't done anything yet
            # in that case, we maintain the existing last_update (i.e., worker creation time)

            candidate_last_update = self.job_set.filter(
                    status__in=[ Job.IN_PROGRESS, Job.DONE, Job.FAILED ]).aggregate(
                            Max('last_update'))['last_update__max']

            if candidate_last_update:
                # in case of rereg, self.last_update will > candidate_last_update and should be retained
                self.last_update = max(self.last_update, candidate_last_update)

            # get the oldest still-queued job (most stale)
            # may return none if there's no pending jobs
            oldest_queue_time = self.job_set.filter(status=Job.QUEUED).aggregate(
                            Min('last_update'))['last_update__min']

            # if I'm expecting to hear from the worker (i.e., jobs are waiting)
            #   if he's not said anything in a long time
            #       then it's dead

            if self.job_set.filter(status__in=[Job.IN_PROGRESS, Job.QUEUED]).exists():
                if not oldest_queue_time: oldest_queue_time = datetime.min # cover when only in_prog exists

                effective_last_update = max(oldest_queue_time, self.last_update)

                if (datetime.now() - effective_last_update).days > settings.DATAMILL_DAYS_UNTIL_WORKER_DEAD:
                    self.make_dead()
                    return

            self.save()

    @reversion.create_revision()
    def fill_from_dict(self, dict):
        # attention: now calls self.save()

        # this method fills in as much as it can, ignoring missing data.
        # if any missing field turns out to be important or if any
        # of the values filled turn out to be bogus we catch it when we
        # call save() on this worker.

        # extraneous fields in the dict are ignored.

        try:
            with transaction.commit_on_success():
                for field in self._meta.fields:
                    if dict.has_key(field.name):
                        setattr(self, field.name, dict[field.name])

                self.save()

                for factor in Factor.objects.all():
                    if dict.has_key(factor.internal_name):
                        if isinstance(dict[factor.internal_name], list):
                            WorkerFeature.objects.filter(worker=self, level__factor__internal_name=factor.internal_name).delete()
                            for level_name in dict[factor.internal_name]:
                                level, created = Level.objects.get_or_create(factor=factor, internal_name=str(level_name))
                                feature, created = WorkerFeature.objects.get_or_create(worker=self, level=level)
                        else:
                            level, created = Level.objects.get_or_create(factor=factor, internal_name=str(dict[factor.internal_name]))
                            # assumes there is only one level per worker and factor pair
                            if WorkerFeature.objects.filter(worker=self, level__factor=level.factor).exists():
                                feature = WorkerFeature.objects.get(worker=self, level__factor=level.factor)
                                feature.level = level
                                feature.save()
                            else:
                                WorkerFeature.objects.create(worker=self, level=level)
                    else:
                        raise Exception('factor is missing in dictionary: {}'.format(factor.internal_name))

        except Exception:
            if Worker.objects.filter(uuid=self.uuid).exists(): # if I was in the db
                self.make_dead()
            raise

    def create_dir(self):
        if not os.path.exists(self.get_dir()):
            os.mkdir(self.get_dir())

            try:
                uid = getpwnam('apache')[2]
                gid = getgrnam('ftp')[2]
                os.chown(self.get_dir(), uid, gid)
                os.chmod(self.get_dir(),
                                stat.S_IRUSR |
                                stat.S_IWUSR |
                                stat.S_IXUSR |
                                stat.S_IRGRP |
                                stat.S_IWGRP |

master/datamill_website/forms.py
from datamill_website.models import Experiment, Package

from django.forms import ModelForm, Textarea
from django import forms
from django.contrib.auth.models import User

class PackageForm(forms.ModelForm):
    class Meta:
        model = Package
        exclude = ('experiment',)

class NumberInput(forms.widgets.TextInput):
    input_type = 'number'

class ExperimentForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea, required=False)
    class Meta:
        model = Experiment
        fields = ['name', 'replicate_count', 'run_on_all_workers', 'tags']

    replicate_count = forms.IntegerField(
            min_value = 1,
            widget = NumberInput(attrs={'data-bind': 'value: numReplicates', 'class': 'input-mini'})
    )

class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

master/datamill_website/templates/datamill_website/experiment_add.html
{% extends "base.html" %}

{% block title %}Create New Experiment{% endblock %}

{% block content %}
{%load i18n %}

    <ul class="breadcrumb">
        <li><a href="/">Home</a> <span class="divider">/</span></li>
        <li><a href="/experiments">Experiments</a> <span class="divider">/</span></li>
        <li class="active">Create New Experiment</li>
    </ul>

    <form class="experiment-wizard form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>

            <!-- Form Name -->
            <legend>Main Settings <span class="caption">Your experiment's essential details</span></legend>

            <!-- Text input-->
            <div class="control-group">
                <label class="control-label required" for="name">Name</label>

                <div class="controls">
                    {{ experiment_form.name }}
                    {% if experiment_form.name.errors %}
                        <div class="alert alert-error">{{ experiment_form.name.errors }}</div>
                    {% else %}
                        <p class="help-block">Enter your experiment name</p>
                    {% endif %}

                </div>
            </div>

          <!-- Text input-->
          <div class="control-group">
            <label class="control-label" for="id_description">Description</label>

            <div class="controls">
              {{ experiment_form.description }}
              {% if experiment_form.description.errors %}
                <div class="alert alert-error">{{ experiment_form.description.errors }}</div>
              {% endif %}
            </div>
          </div>

            <!-- Text input-->
            <div class="control-group">
                <label class="control-label" for="replicate_count">Replicate Count</label>

                <div class="controls">
                    <span class="input-append">
                        {{ experiment_form.replicate_count }}
                        <span class="add-on">#</span>
                    </span>


                    {% if experiment_form.replicate_count.errors %}
                        <div class="alert alert-error">{{ experiment_form.replicate_count.errors }}</div>
                    {% else %}
                        <p class="help-block">Enter how many times each job should execute</p>
                    {% endif %}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label required" for="previous_packages">File(s)</label>

                <div class="controls">
                    {{ packageset.management_form }}
                    <div>
                        {% for package in previous_packages %}
                            <div class="checkbox">
                                <label>
                                    <input id="previous_packages" name="previous_packages" type="checkbox"
                                           value="{{ package.id }}"
                                           checked/>{{ package.filename }}
                                </label>
                            </div>
                        {% endfor %}
                    </div>
                    {% for package in packageset %}
                        <div class='add-file'>
                            <label for="id_{{ package.file.html_name }}"
                                   class="element-invisible">{{ package.file.label_tag }}</label>
                            {{ package.file }}
                        </div>
                    {% endfor %}
                    {% if packageset.errors %}
                        <div class="alert alert-error">
                            {% for line in packageset.errors %}
                                {{ line.file }}
                            {% endfor %}
                        </div>
                    {% endif %}

                    <input type="button" value="Add file" id="btn-add-file" class="btn btn-danger">
                    <input type="button" value="Remove file" id="btn-remove-file" class="btn">
                </div>
            </div>

            <div class="control-group">
              <label class="control-label required" for="id_tags">Tags</label>

                <div class="controls">
                  {{ experiment_form.tags }}
                  {% if experiment_form.tags.errors %}
                        <div class="alert alert-error">{{ experiment_form.tags.errors }}</div>
                    {% endif %}
                </div>
            </div>

        </fieldset>

        {% if experiment_form.non_field_errors %}
            <div class="alert alert-error">{{ experiment_form.non_field_errors }}</div>
        {% endif %}

        <fieldset class="hardware">
            <legend>Hardware Factors <span class="caption">Where can your experiment run? <i class="icon-info-sign" data-toggle="tooltip" title="Please exclude platforms your experiment is incompatible with. We'll pick the machines that will run your code from the remaining pool of eligible workers."></i></span></legend>
            {% for choice in hardware_choices %}

                <div class="control-group">
                    <label class="control-label">
                        {{ choice.name }}
                    </label>
                    <div class="controls">
                        {% for option in choice.get_levels %}
                            <label class="checkbox inline">
                                <input type="checkbox" value="{{ option }}"
                                       data-bind="checked: options.{{ choice.internal_name }}">
                                {% trans option %}
                            </label>
                        {% endfor %}
                        <p class="help-block">{{ choice.description }}</p>
                    </div>
                </div>
            {% endfor %}
            <!-- ko foreach: sliders.hardware -->
            <div class="control-group">
                <label class="control-label" data-bind="text: name">
                </label>
                <div class="controls slider-container" data-bind="template: { name: 'slider-template', data: $data }"></div>
            </div>
            <!-- /ko -->


            <div class="control-group">
                <label class="control-label">
                    Machine Pool
                </label>
                <div class="controls">
                    <div class="well" data-bind="foreach: machines.all">
                        <a class="machines" data-toggle="popover" data-trigger="hover" data-html="true" data-placement="top" data-bind="click: $root.machines.details, popover: { content: 'Arch: '+workers[$data].cpu_arch+'<br />Core Count: '+workers[$data].num_cpus+'<br />CPU MHz: '+workers[$data].cpu_mhz+'<br />RAM: '+Humanize.fileSize(workers[$data].ram_sz*1024), title: 'Worker: ' + $data }, css: { gray: !$root.machines.selected().find($data) }" href="#"><span data-bind="text: $data"></span></a>
                    </div>
                    <p data-bind="css: { error: machines.selected().length === 0 }" class="help-block">There are <span class="badge" data-bind="text: machines.selected().length"></span> machines eligible to run your experiment. <span data-bind="visible: machines.selected().length > 0">Eligible machines are highlighted in red and their architectures are <span data-bind="text: architectures_text"></span>. </span></p>
                </div>
            </div>
        </fieldset>
        <fieldset class="software">
            <legend>Software Factors <span class="caption">Select which software settings you would like to explore. <i class="icon-info-sign" data-toggle="tooltip" title="We've selected sane defaults for you, so you probably just have to add extra levels you're interested in. Each factor combination is exhaustively explored, so beware of combinatorial explosion!"></i></span></legend>
            <div class="well">
                <h4>Known Factors</h4>
                {% for choice in software_choices.known %}
                    {% include "sections/software_checkbox.html" %}
                {% endfor %}
            </div>
            <div class="well">
                <h4>Hidden Factors</h4>
                {% for choice in software_choices.hidden %}
                    {% include "sections/software_checkbox.html" %}
                {% endfor %}
            </div>
            <hr/>
            <div class="control-group">
                <label class="control-label" data-bind="css: { error: numJobs() == 0 }">
                    Jobs per Worker
                </label>
                <div class="controls">
                    <div class="well"><span data-bind="text: numJobs"></span><span class="badge" data-bind="css: jobsStatus, text: jobStatusText"></span></div>
                    <p class="help-block">This is the number of jobs that will be created per machine. The higher the number of jobs per machine, the lower the priority of your experiment will be, and the longer your experiment will take to finish.</p>
                </div>
            </div>

        </fieldset>

        {% if admin %}
        <fieldset class="admin">
            <legend>Administrative Options <span class="caption">Use with care!</span></legend>

            <div class="control-group">
                <label class="control-label">
                    Run on all Workers
                </label>
                <div class="controls">
                    <label class="checkbox inline">
                        <input type="checkbox" name="run_on_all_workers">
                        Forces jobs to be scheduled on all workers.
                    </label>
                </div>
            </div>
        </fieldset>
        {% endif %}

    
        <input type="submit" value="Submit" class="pull-right submit btn btn-danger" data-bind="click: save"/>
        <input type="hidden" name="factorSettings" data-bind="value: ko.toJSON(viewModel)"/>

    </form>
    <div id="dialog" title="" class="ui-helper-hidden">
        <p>Check form for errors</p>
    </div>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript">
        var factors ={{ factors|safe }};
        var constants ={{ constants|safe }};
        var features ={{ features|safe }};
        var workers ={{ workers|safe }};
    </script>
    <script type="text/html" id="slider-template">
        <div>
            <div class="slider-container">
                <div class="slider"
                     data-bind="wijslider: { values: ranges, min: min, max: max, slide: slide, range: true }">
                </div>
                <div class="min"></div>
                <div class="max"></div>
            </div>
        </div>

        <p class="help-block" data-bind="text: description"></p>
    </script>
{% endblock %}

master/datamill_website/templates/datamill_website/experiment_list.html
{% extends "base.html" %}

{% block title %}Experiments{% endblock %}

{% block content %}

    <ul class="breadcrumb">
      <li><a href="/">Home</a> <span class="divider">/</span></li>
      <li class="active">Experiments</li>
    </ul>

    <div class="row">
        <div class="span9">
            <h1>My Experiments</h1>
        </div>
        <div class="span3">
            <div class="button-outer">
                <br><p class="text-right"><a href="/experiment/add/" class="btn btn-danger">Create new experiment</a></p>
            </div>
	</div>
    </div>
    {% with list=experiment_list %}
        {% include "datamill_website/pagiantion.html" %}
    {% endwith %}
    {% if experiment_list %}
    <table class="table">
        <thead>
            <tr>
                <th><a href="?order_by={% if order_by == 'name' %}-{% endif %}name">Name</a></th>
                <th></th>
                <th></th>
                <th></th>
                <th><a href="?order_by={% if order_by == 'submission_date' %}-{% endif %}submission_date">Submitted</a></th>
                <th><a href="?order_by={% if order_by == 'status' %}-{% endif %}status">Status</a></th>
                <th>Completed</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
        {% for e in experiment_list %}
            <tr>
                <td><a href="/experiment/{{ e.id }}" id="experimentName{{ e.id }}">{{ e.name }}</a></td>
                <td><a href="#" data-id="{{ e.id }}" class="img-link edit-experiment"><span class="ui-icon ui-icon-pencil"></span></a></td>
                <td><a href="/experiment/clone/{{ e.id }}" class="img-link"><span class="ui-icon ui-icon-copy"></span></a></td>
                <td><a href="/experiment/delete/{{ e.id }}" class="img-link"><span class="ui-icon ui-icon-trash"></span></a></td>
                <td>{{ e.submission_date }}</td>
                <td>{{ e.get_status_display }}</td>
                <td>{{ e.get_completion_percentage }} %</td>
                <td><a href="/experiment/{{ e.id }}">View details</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
      <div class="alert alert-info">
        You do not have any experiments yet. Please <a href="/experiment/add/">submit an experiment</a>.
      </div>
      {% endif %}

    {% for e in experiment_list %}
        <div id="dialog{{ e.id }}" data-id="{{ e.id }}" class="experimentDialog hide" title="Edit experiment"> 
            <form action="{% url 'experiment_save' e.id %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <label>Title</label>
                    <input name="name" type="text" value="{{ e.name }}"/>
                    <label>Description</label>
                    <textarea name="description" rows="5">{{ e.description }}</textarea>
                    <input type="hidden" name="replicate_count" value="{{ e.replicate_count }}">
                </fieldset>
            </form>
        </div> 
    {% endfor %}
{% endblock %}

master/datamill_website/templates/datamill_website/job_list.html
{% extends "base.html" %}

{% block title %}Jobs{% endblock %}

{% load static %}

{% block content %}

    <ul class="breadcrumb">
      <li><a href="/">Home</a> <span class="divider">/</span></li>
      <li class="active">Jobs</li>
    </ul>

    <h1>My Jobs</h1>
    {% with list=job_list %}
        {% include "datamill_website/pagiantion.html" %}
    {% endwith %}
    {% if job_list.count > 0 %}
    <table class="table">
        <thead>
            <tr>
                <th><a href="?order_by={% if order_by == 'experiment' %}-{% endif %}experiment">Experiment</a></th>
                <th><a href="?order_by={% if order_by == 'package' %}-{% endif %}package">Package</a></th>
                <th><a href="?order_by={% if order_by == 'worker' %}-{% endif %}worker">Worker</a></th>
                <th><a href="?order_by={% if order_by == 'status' %}-{% endif %}status">Status</a></th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
        {% for j in job_list %}
        <tr>
            <td><a href="/experiment/{{ j.experiment.id }}">{{ j.experiment }}</a></td>
            <td><a href="/package/{{ j.package.id }}/">{{ j.package }}</a></td>
            <td><a href="/worker/{{ j.worker.id }}">{{ j.worker.hostname }}</a></td>
            <td>{{ j.get_status_display }}</td>
            <td><a href="/job/{{ j.id }}">View details</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>   
    {% else %}
    <div class="alert alert-info">
        You do not have any jobs yet. Please <a href="/experiment/add/">submit an experiment</a>.
    </div>
    {% endif %}

{% endblock %}